/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiquidationRouteImport } from './routes/liquidation'
import { Route as InsiderTradingRouteImport } from './routes/insider-trading'
import { Route as EmbedKitRouteImport } from './routes/embed-kit'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as DcaRouteImport } from './routes/dca'
import { Route as BearMarketRouteImport } from './routes/bear-market'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesWhyBtc500ExistsRouteImport } from './routes/articles.why-btc500-exists'
import { Route as ArticlesRuplRouteImport } from './routes/articles.rupl'
import { Route as ArticlesOndoFinanceTokenizationRouteImport } from './routes/articles.ondo-finance-tokenization'
import { Route as ArticlesClarityActRouteImport } from './routes/articles.clarity-act'
import { Route as ArticlesBtc500StrategyRouteImport } from './routes/articles.btc500-strategy'
import { Route as ArticlesBearMarketAccumulationRouteImport } from './routes/articles.bear-market-accumulation'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidationRoute = LiquidationRouteImport.update({
  id: '/liquidation',
  path: '/liquidation',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderTradingRoute = InsiderTradingRouteImport.update({
  id: '/insider-trading',
  path: '/insider-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKitRoute = EmbedKitRouteImport.update({
  id: '/embed-kit',
  path: '/embed-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const DcaRoute = DcaRouteImport.update({
  id: '/dca',
  path: '/dca',
  getParentRoute: () => rootRouteImport,
} as any)
const BearMarketRoute = BearMarketRouteImport.update({
  id: '/bear-market',
  path: '/bear-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesWhyBtc500ExistsRoute = ArticlesWhyBtc500ExistsRouteImport.update({
  id: '/why-btc500-exists',
  path: '/why-btc500-exists',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesRuplRoute = ArticlesRuplRouteImport.update({
  id: '/rupl',
  path: '/rupl',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesOndoFinanceTokenizationRoute =
  ArticlesOndoFinanceTokenizationRouteImport.update({
    id: '/ondo-finance-tokenization',
    path: '/ondo-finance-tokenization',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesClarityActRoute = ArticlesClarityActRouteImport.update({
  id: '/clarity-act',
  path: '/clarity-act',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBtc500StrategyRoute = ArticlesBtc500StrategyRouteImport.update({
  id: '/btc500-strategy',
  path: '/btc500-strategy',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBearMarketAccumulationRoute =
  ArticlesBearMarketAccumulationRouteImport.update({
    id: '/bear-market-accumulation',
    path: '/bear-market-accumulation',
    getParentRoute: () => ArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/simulator': typeof SimulatorRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/simulator'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/why-btc500-exists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/simulator'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/why-btc500-exists'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/simulator'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/why-btc500-exists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  BearMarketRoute: typeof BearMarketRoute
  DcaRoute: typeof DcaRoute
  EmbedRoute: typeof EmbedRoute
  EmbedKitRoute: typeof EmbedKitRoute
  InsiderTradingRoute: typeof InsiderTradingRoute
  LiquidationRoute: typeof LiquidationRoute
  NewsRoute: typeof NewsRoute
  SimulatorRoute: typeof SimulatorRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidation': {
      id: '/liquidation'
      path: '/liquidation'
      fullPath: '/liquidation'
      preLoaderRoute: typeof LiquidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider-trading': {
      id: '/insider-trading'
      path: '/insider-trading'
      fullPath: '/insider-trading'
      preLoaderRoute: typeof InsiderTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-kit': {
      id: '/embed-kit'
      path: '/embed-kit'
      fullPath: '/embed-kit'
      preLoaderRoute: typeof EmbedKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dca': {
      id: '/dca'
      path: '/dca'
      fullPath: '/dca'
      preLoaderRoute: typeof DcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bear-market': {
      id: '/bear-market'
      path: '/bear-market'
      fullPath: '/bear-market'
      preLoaderRoute: typeof BearMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/why-btc500-exists': {
      id: '/articles/why-btc500-exists'
      path: '/why-btc500-exists'
      fullPath: '/articles/why-btc500-exists'
      preLoaderRoute: typeof ArticlesWhyBtc500ExistsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/rupl': {
      id: '/articles/rupl'
      path: '/rupl'
      fullPath: '/articles/rupl'
      preLoaderRoute: typeof ArticlesRuplRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/ondo-finance-tokenization': {
      id: '/articles/ondo-finance-tokenization'
      path: '/ondo-finance-tokenization'
      fullPath: '/articles/ondo-finance-tokenization'
      preLoaderRoute: typeof ArticlesOndoFinanceTokenizationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/clarity-act': {
      id: '/articles/clarity-act'
      path: '/clarity-act'
      fullPath: '/articles/clarity-act'
      preLoaderRoute: typeof ArticlesClarityActRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/btc500-strategy': {
      id: '/articles/btc500-strategy'
      path: '/btc500-strategy'
      fullPath: '/articles/btc500-strategy'
      preLoaderRoute: typeof ArticlesBtc500StrategyRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bear-market-accumulation': {
      id: '/articles/bear-market-accumulation'
      path: '/bear-market-accumulation'
      fullPath: '/articles/bear-market-accumulation'
      preLoaderRoute: typeof ArticlesBearMarketAccumulationRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesBearMarketAccumulationRoute: typeof ArticlesBearMarketAccumulationRoute
  ArticlesBtc500StrategyRoute: typeof ArticlesBtc500StrategyRoute
  ArticlesClarityActRoute: typeof ArticlesClarityActRoute
  ArticlesOndoFinanceTokenizationRoute: typeof ArticlesOndoFinanceTokenizationRoute
  ArticlesRuplRoute: typeof ArticlesRuplRoute
  ArticlesWhyBtc500ExistsRoute: typeof ArticlesWhyBtc500ExistsRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesBearMarketAccumulationRoute: ArticlesBearMarketAccumulationRoute,
  ArticlesBtc500StrategyRoute: ArticlesBtc500StrategyRoute,
  ArticlesClarityActRoute: ArticlesClarityActRoute,
  ArticlesOndoFinanceTokenizationRoute: ArticlesOndoFinanceTokenizationRoute,
  ArticlesRuplRoute: ArticlesRuplRoute,
  ArticlesWhyBtc500ExistsRoute: ArticlesWhyBtc500ExistsRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  BearMarketRoute: BearMarketRoute,
  DcaRoute: DcaRoute,
  EmbedRoute: EmbedRoute,
  EmbedKitRoute: EmbedKitRoute,
  InsiderTradingRoute: InsiderTradingRoute,
  LiquidationRoute: LiquidationRoute,
  NewsRoute: NewsRoute,
  SimulatorRoute: SimulatorRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
