/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiquidationRouteImport } from './routes/liquidation'
import { Route as InsiderTradingRouteImport } from './routes/insider-trading'
import { Route as HalvingDatesRouteImport } from './routes/halving-dates'
import { Route as EmbedKitRouteImport } from './routes/embed-kit'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as DcaRouteImport } from './routes/dca'
import { Route as BearMarketRouteImport } from './routes/bear-market'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesWhyBtc500ExistsRouteImport } from './routes/articles.why-btc500-exists'
import { Route as ArticlesStrongestHandsRouteImport } from './routes/articles.strongest-hands'
import { Route as ArticlesSolarEclipseBitcoinHalvingRouteImport } from './routes/articles.solar-eclipse-bitcoin-halving'
import { Route as ArticlesSecCancelsRegulationCryptoRouteImport } from './routes/articles.sec-cancels-regulation-crypto'
import { Route as ArticlesRuplRouteImport } from './routes/articles.rupl'
import { Route as ArticlesOndoFinanceTokenizationRouteImport } from './routes/articles.ondo-finance-tokenization'
import { Route as ArticlesGoldmanVsBlackrockRouteImport } from './routes/articles.goldman-vs-blackrock'
import { Route as ArticlesClarityActRouteImport } from './routes/articles.clarity-act'
import { Route as ArticlesBtc500StrategyRouteImport } from './routes/articles.btc500-strategy'
import { Route as ArticlesBitcoinWeekAheadRouteImport } from './routes/articles.bitcoin-week-ahead'
import { Route as ArticlesBitcoinVolatilityRouteImport } from './routes/articles.bitcoin-volatility'
import { Route as ArticlesBitcoinInfrastructureExploitsRouteImport } from './routes/articles.bitcoin-infrastructure-exploits'
import { Route as ArticlesBip110RejectionRouteImport } from './routes/articles.bip-110-rejection'
import { Route as ArticlesBearMarketAccumulationRouteImport } from './routes/articles.bear-market-accumulation'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidationRoute = LiquidationRouteImport.update({
  id: '/liquidation',
  path: '/liquidation',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderTradingRoute = InsiderTradingRouteImport.update({
  id: '/insider-trading',
  path: '/insider-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const HalvingDatesRoute = HalvingDatesRouteImport.update({
  id: '/halving-dates',
  path: '/halving-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKitRoute = EmbedKitRouteImport.update({
  id: '/embed-kit',
  path: '/embed-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const DcaRoute = DcaRouteImport.update({
  id: '/dca',
  path: '/dca',
  getParentRoute: () => rootRouteImport,
} as any)
const BearMarketRoute = BearMarketRouteImport.update({
  id: '/bear-market',
  path: '/bear-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesWhyBtc500ExistsRoute = ArticlesWhyBtc500ExistsRouteImport.update({
  id: '/why-btc500-exists',
  path: '/why-btc500-exists',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesStrongestHandsRoute = ArticlesStrongestHandsRouteImport.update({
  id: '/strongest-hands',
  path: '/strongest-hands',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSolarEclipseBitcoinHalvingRoute =
  ArticlesSolarEclipseBitcoinHalvingRouteImport.update({
    id: '/solar-eclipse-bitcoin-halving',
    path: '/solar-eclipse-bitcoin-halving',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSecCancelsRegulationCryptoRoute =
  ArticlesSecCancelsRegulationCryptoRouteImport.update({
    id: '/sec-cancels-regulation-crypto',
    path: '/sec-cancels-regulation-crypto',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesRuplRoute = ArticlesRuplRouteImport.update({
  id: '/rupl',
  path: '/rupl',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesOndoFinanceTokenizationRoute =
  ArticlesOndoFinanceTokenizationRouteImport.update({
    id: '/ondo-finance-tokenization',
    path: '/ondo-finance-tokenization',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesGoldmanVsBlackrockRoute =
  ArticlesGoldmanVsBlackrockRouteImport.update({
    id: '/goldman-vs-blackrock',
    path: '/goldman-vs-blackrock',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesClarityActRoute = ArticlesClarityActRouteImport.update({
  id: '/clarity-act',
  path: '/clarity-act',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBtc500StrategyRoute = ArticlesBtc500StrategyRouteImport.update({
  id: '/btc500-strategy',
  path: '/btc500-strategy',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBitcoinWeekAheadRoute =
  ArticlesBitcoinWeekAheadRouteImport.update({
    id: '/bitcoin-week-ahead',
    path: '/bitcoin-week-ahead',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBitcoinVolatilityRoute =
  ArticlesBitcoinVolatilityRouteImport.update({
    id: '/bitcoin-volatility',
    path: '/bitcoin-volatility',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBitcoinInfrastructureExploitsRoute =
  ArticlesBitcoinInfrastructureExploitsRouteImport.update({
    id: '/bitcoin-infrastructure-exploits',
    path: '/bitcoin-infrastructure-exploits',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBip110RejectionRoute = ArticlesBip110RejectionRouteImport.update({
  id: '/bip-110-rejection',
  path: '/bip-110-rejection',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBearMarketAccumulationRoute =
  ArticlesBearMarketAccumulationRouteImport.update({
    id: '/bear-market-accumulation',
    path: '/bear-market-accumulation',
    getParentRoute: () => ArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/halving-dates': typeof HalvingDatesRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/bip-110-rejection': typeof ArticlesBip110RejectionRoute
  '/articles/bitcoin-infrastructure-exploits': typeof ArticlesBitcoinInfrastructureExploitsRoute
  '/articles/bitcoin-volatility': typeof ArticlesBitcoinVolatilityRoute
  '/articles/bitcoin-week-ahead': typeof ArticlesBitcoinWeekAheadRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/goldman-vs-blackrock': typeof ArticlesGoldmanVsBlackrockRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/sec-cancels-regulation-crypto': typeof ArticlesSecCancelsRegulationCryptoRoute
  '/articles/solar-eclipse-bitcoin-halving': typeof ArticlesSolarEclipseBitcoinHalvingRoute
  '/articles/strongest-hands': typeof ArticlesStrongestHandsRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/halving-dates': typeof HalvingDatesRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/bip-110-rejection': typeof ArticlesBip110RejectionRoute
  '/articles/bitcoin-infrastructure-exploits': typeof ArticlesBitcoinInfrastructureExploitsRoute
  '/articles/bitcoin-volatility': typeof ArticlesBitcoinVolatilityRoute
  '/articles/bitcoin-week-ahead': typeof ArticlesBitcoinWeekAheadRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/goldman-vs-blackrock': typeof ArticlesGoldmanVsBlackrockRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/sec-cancels-regulation-crypto': typeof ArticlesSecCancelsRegulationCryptoRoute
  '/articles/solar-eclipse-bitcoin-halving': typeof ArticlesSolarEclipseBitcoinHalvingRoute
  '/articles/strongest-hands': typeof ArticlesStrongestHandsRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/bear-market': typeof BearMarketRoute
  '/dca': typeof DcaRoute
  '/embed': typeof EmbedRoute
  '/embed-kit': typeof EmbedKitRoute
  '/halving-dates': typeof HalvingDatesRoute
  '/insider-trading': typeof InsiderTradingRoute
  '/liquidation': typeof LiquidationRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/articles/bear-market-accumulation': typeof ArticlesBearMarketAccumulationRoute
  '/articles/bip-110-rejection': typeof ArticlesBip110RejectionRoute
  '/articles/bitcoin-infrastructure-exploits': typeof ArticlesBitcoinInfrastructureExploitsRoute
  '/articles/bitcoin-volatility': typeof ArticlesBitcoinVolatilityRoute
  '/articles/bitcoin-week-ahead': typeof ArticlesBitcoinWeekAheadRoute
  '/articles/btc500-strategy': typeof ArticlesBtc500StrategyRoute
  '/articles/clarity-act': typeof ArticlesClarityActRoute
  '/articles/goldman-vs-blackrock': typeof ArticlesGoldmanVsBlackrockRoute
  '/articles/ondo-finance-tokenization': typeof ArticlesOndoFinanceTokenizationRoute
  '/articles/rupl': typeof ArticlesRuplRoute
  '/articles/sec-cancels-regulation-crypto': typeof ArticlesSecCancelsRegulationCryptoRoute
  '/articles/solar-eclipse-bitcoin-halving': typeof ArticlesSolarEclipseBitcoinHalvingRoute
  '/articles/strongest-hands': typeof ArticlesStrongestHandsRoute
  '/articles/why-btc500-exists': typeof ArticlesWhyBtc500ExistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/halving-dates'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/bip-110-rejection'
    | '/articles/bitcoin-infrastructure-exploits'
    | '/articles/bitcoin-volatility'
    | '/articles/bitcoin-week-ahead'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/goldman-vs-blackrock'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/sec-cancels-regulation-crypto'
    | '/articles/solar-eclipse-bitcoin-halving'
    | '/articles/strongest-hands'
    | '/articles/why-btc500-exists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/halving-dates'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/bip-110-rejection'
    | '/articles/bitcoin-infrastructure-exploits'
    | '/articles/bitcoin-volatility'
    | '/articles/bitcoin-week-ahead'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/goldman-vs-blackrock'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/sec-cancels-regulation-crypto'
    | '/articles/solar-eclipse-bitcoin-halving'
    | '/articles/strongest-hands'
    | '/articles/why-btc500-exists'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/bear-market'
    | '/dca'
    | '/embed'
    | '/embed-kit'
    | '/halving-dates'
    | '/insider-trading'
    | '/liquidation'
    | '/news'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/timeline'
    | '/articles/bear-market-accumulation'
    | '/articles/bip-110-rejection'
    | '/articles/bitcoin-infrastructure-exploits'
    | '/articles/bitcoin-volatility'
    | '/articles/bitcoin-week-ahead'
    | '/articles/btc500-strategy'
    | '/articles/clarity-act'
    | '/articles/goldman-vs-blackrock'
    | '/articles/ondo-finance-tokenization'
    | '/articles/rupl'
    | '/articles/sec-cancels-regulation-crypto'
    | '/articles/solar-eclipse-bitcoin-halving'
    | '/articles/strongest-hands'
    | '/articles/why-btc500-exists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  BearMarketRoute: typeof BearMarketRoute
  DcaRoute: typeof DcaRoute
  EmbedRoute: typeof EmbedRoute
  EmbedKitRoute: typeof EmbedKitRoute
  HalvingDatesRoute: typeof HalvingDatesRoute
  InsiderTradingRoute: typeof InsiderTradingRoute
  LiquidationRoute: typeof LiquidationRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  SimulatorRoute: typeof SimulatorRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidation': {
      id: '/liquidation'
      path: '/liquidation'
      fullPath: '/liquidation'
      preLoaderRoute: typeof LiquidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider-trading': {
      id: '/insider-trading'
      path: '/insider-trading'
      fullPath: '/insider-trading'
      preLoaderRoute: typeof InsiderTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halving-dates': {
      id: '/halving-dates'
      path: '/halving-dates'
      fullPath: '/halving-dates'
      preLoaderRoute: typeof HalvingDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-kit': {
      id: '/embed-kit'
      path: '/embed-kit'
      fullPath: '/embed-kit'
      preLoaderRoute: typeof EmbedKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dca': {
      id: '/dca'
      path: '/dca'
      fullPath: '/dca'
      preLoaderRoute: typeof DcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bear-market': {
      id: '/bear-market'
      path: '/bear-market'
      fullPath: '/bear-market'
      preLoaderRoute: typeof BearMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/why-btc500-exists': {
      id: '/articles/why-btc500-exists'
      path: '/why-btc500-exists'
      fullPath: '/articles/why-btc500-exists'
      preLoaderRoute: typeof ArticlesWhyBtc500ExistsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/strongest-hands': {
      id: '/articles/strongest-hands'
      path: '/strongest-hands'
      fullPath: '/articles/strongest-hands'
      preLoaderRoute: typeof ArticlesStrongestHandsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/solar-eclipse-bitcoin-halving': {
      id: '/articles/solar-eclipse-bitcoin-halving'
      path: '/solar-eclipse-bitcoin-halving'
      fullPath: '/articles/solar-eclipse-bitcoin-halving'
      preLoaderRoute: typeof ArticlesSolarEclipseBitcoinHalvingRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/sec-cancels-regulation-crypto': {
      id: '/articles/sec-cancels-regulation-crypto'
      path: '/sec-cancels-regulation-crypto'
      fullPath: '/articles/sec-cancels-regulation-crypto'
      preLoaderRoute: typeof ArticlesSecCancelsRegulationCryptoRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/rupl': {
      id: '/articles/rupl'
      path: '/rupl'
      fullPath: '/articles/rupl'
      preLoaderRoute: typeof ArticlesRuplRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/ondo-finance-tokenization': {
      id: '/articles/ondo-finance-tokenization'
      path: '/ondo-finance-tokenization'
      fullPath: '/articles/ondo-finance-tokenization'
      preLoaderRoute: typeof ArticlesOndoFinanceTokenizationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/goldman-vs-blackrock': {
      id: '/articles/goldman-vs-blackrock'
      path: '/goldman-vs-blackrock'
      fullPath: '/articles/goldman-vs-blackrock'
      preLoaderRoute: typeof ArticlesGoldmanVsBlackrockRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/clarity-act': {
      id: '/articles/clarity-act'
      path: '/clarity-act'
      fullPath: '/articles/clarity-act'
      preLoaderRoute: typeof ArticlesClarityActRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/btc500-strategy': {
      id: '/articles/btc500-strategy'
      path: '/btc500-strategy'
      fullPath: '/articles/btc500-strategy'
      preLoaderRoute: typeof ArticlesBtc500StrategyRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bitcoin-week-ahead': {
      id: '/articles/bitcoin-week-ahead'
      path: '/bitcoin-week-ahead'
      fullPath: '/articles/bitcoin-week-ahead'
      preLoaderRoute: typeof ArticlesBitcoinWeekAheadRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bitcoin-volatility': {
      id: '/articles/bitcoin-volatility'
      path: '/bitcoin-volatility'
      fullPath: '/articles/bitcoin-volatility'
      preLoaderRoute: typeof ArticlesBitcoinVolatilityRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bitcoin-infrastructure-exploits': {
      id: '/articles/bitcoin-infrastructure-exploits'
      path: '/bitcoin-infrastructure-exploits'
      fullPath: '/articles/bitcoin-infrastructure-exploits'
      preLoaderRoute: typeof ArticlesBitcoinInfrastructureExploitsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bip-110-rejection': {
      id: '/articles/bip-110-rejection'
      path: '/bip-110-rejection'
      fullPath: '/articles/bip-110-rejection'
      preLoaderRoute: typeof ArticlesBip110RejectionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/bear-market-accumulation': {
      id: '/articles/bear-market-accumulation'
      path: '/bear-market-accumulation'
      fullPath: '/articles/bear-market-accumulation'
      preLoaderRoute: typeof ArticlesBearMarketAccumulationRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesBearMarketAccumulationRoute: typeof ArticlesBearMarketAccumulationRoute
  ArticlesBip110RejectionRoute: typeof ArticlesBip110RejectionRoute
  ArticlesBitcoinInfrastructureExploitsRoute: typeof ArticlesBitcoinInfrastructureExploitsRoute
  ArticlesBitcoinVolatilityRoute: typeof ArticlesBitcoinVolatilityRoute
  ArticlesBitcoinWeekAheadRoute: typeof ArticlesBitcoinWeekAheadRoute
  ArticlesBtc500StrategyRoute: typeof ArticlesBtc500StrategyRoute
  ArticlesClarityActRoute: typeof ArticlesClarityActRoute
  ArticlesGoldmanVsBlackrockRoute: typeof ArticlesGoldmanVsBlackrockRoute
  ArticlesOndoFinanceTokenizationRoute: typeof ArticlesOndoFinanceTokenizationRoute
  ArticlesRuplRoute: typeof ArticlesRuplRoute
  ArticlesSecCancelsRegulationCryptoRoute: typeof ArticlesSecCancelsRegulationCryptoRoute
  ArticlesSolarEclipseBitcoinHalvingRoute: typeof ArticlesSolarEclipseBitcoinHalvingRoute
  ArticlesStrongestHandsRoute: typeof ArticlesStrongestHandsRoute
  ArticlesWhyBtc500ExistsRoute: typeof ArticlesWhyBtc500ExistsRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesBearMarketAccumulationRoute: ArticlesBearMarketAccumulationRoute,
  ArticlesBip110RejectionRoute: ArticlesBip110RejectionRoute,
  ArticlesBitcoinInfrastructureExploitsRoute:
    ArticlesBitcoinInfrastructureExploitsRoute,
  ArticlesBitcoinVolatilityRoute: ArticlesBitcoinVolatilityRoute,
  ArticlesBitcoinWeekAheadRoute: ArticlesBitcoinWeekAheadRoute,
  ArticlesBtc500StrategyRoute: ArticlesBtc500StrategyRoute,
  ArticlesClarityActRoute: ArticlesClarityActRoute,
  ArticlesGoldmanVsBlackrockRoute: ArticlesGoldmanVsBlackrockRoute,
  ArticlesOndoFinanceTokenizationRoute: ArticlesOndoFinanceTokenizationRoute,
  ArticlesRuplRoute: ArticlesRuplRoute,
  ArticlesSecCancelsRegulationCryptoRoute:
    ArticlesSecCancelsRegulationCryptoRoute,
  ArticlesSolarEclipseBitcoinHalvingRoute:
    ArticlesSolarEclipseBitcoinHalvingRoute,
  ArticlesStrongestHandsRoute: ArticlesStrongestHandsRoute,
  ArticlesWhyBtc500ExistsRoute: ArticlesWhyBtc500ExistsRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  BearMarketRoute: BearMarketRoute,
  DcaRoute: DcaRoute,
  EmbedRoute: EmbedRoute,
  EmbedKitRoute: EmbedKitRoute,
  HalvingDatesRoute: HalvingDatesRoute,
  InsiderTradingRoute: InsiderTradingRoute,
  LiquidationRoute: LiquidationRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  SimulatorRoute: SimulatorRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
